version: "3.8"

services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.production

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5037:8080"
    depends_on:
      - mssql
    networks:
      - mssql-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_2022
    environment:
      SA_PASSWORD: StrongPassword1!
      ACCEPT_EULA: Y
    ports:
      - "1434:1433"  # Changed port mapping to 1434
    volumes:
      - ./data:/var/opt/mssql/data
      - ./backup:/var/opt/mssql/backup
    networks:
      - mssql-network

networks:
  mssql-network:
    driver: bridge
